nombre: Windows-RDP

en: workflow_dispatch

trabajos:
  construir:

    runs-on: windows-latest
    minutos de espera: 9999

    pasos:
    - nombre: Descargar Ngrok.
      ejecutar: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/aiko-chan-ai/windows-rdp/main/start.bat -OutFile start.bat
 Fondo de pantalla Invoke-WebRequest https://raw.githubusercontent.com/aiko-chan-ai/windows-rdp/main/wallpaper.png -OutFile.png
 Fondo de pantalla Invoke-WebRequest https://raw.githubusercontent.com/aiko-chan-ai/windows-rdp/main/wallpaper.bat -OutFile.bat
 Bucle Invoke-WebRequest https://raw.githubusercontent.com/aiko-chan-ai/windows-rdp/main/loop.bat -OutFile.bat
    - nombre: Descargar Launcher.
      ejecutar: |
        Invoke-WebRequest https://raw.githubusercontent.com/aiko-chan-ai/windows-rdp/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/aiko-chan-ai/windows-rdp/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
        Invoke-WebRequest https://github.com/DinhPhuc/windows-rdp/raw/main/launcher/Ganti%20Password.exe -OutFile "Ganti Password.exe"
    - nombre: Extraer archivo Ngrok.
      ejecutar: Expand-Archive ngrok.zip
    - nombre: Connect Ngrok.
      ejecutar: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secretos. NGROK_AUTH_TOKEN }}
    - nombre: Action Access RDP.
      ejecutar: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
 Enable-NetFirewallRule -DisplayGroup "Escritorio remoto"
 Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Valor 1
 copiar fondo de pantalla.png D:\a\wallpaper.png
 copiar fondo de pantalla.bat D:\a\wallpaper.bat
 copie Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
 Copie "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
 copie "Ganti Password.exe" "C:\Users\Public\Desktop\Ganti Password.exe"
    - nombre: Hacer túneles
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - nombre: Conecte RDP CPU 2 Core - 7GB Ram - 256 SSD.
      ejecutar: cmd /c inicio.bat
    - nombre: ¡Implementación exitosa! Puede cerrar la pestaña ahora.
      ejecutar: cmd /c loop.bat
